### ISSUE TITLE
Can't add more than one olClass or liClass

### ISSUE THREAD

**Issue by friartuck6000** [UFHealth/butr.js#11]
JS `Element.classList.add()` does not allow a space-separated string for adding multiple classes, so the class-setting options across butter won't allow users to provide more than one class.

**See:**
- https://github.com/UFHealth/butr.js/blob/master/src/butr.js#L295
- https://github.com/UFHealth/butr.js/blob/master/src/butr.js#L295

**Error:**
```
DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('list-reset db') contains HTML space characters, which are not valid in tokens.
```

Any objections on allowing multiple classes via one of the following?

```js
butr.autoSidebar({
  // using a space-separated string
  olClass: 'list-reset list-class-1 list-class-2',
  // or using an array
  liClass: ['item-class-1', 'item-class-2']
})
```

**Comment by billcolumbia** [comment]
Let's do space separated so it works like a normal HTML class would.

**Comment by billcolumbia** [comment]
Well [IE has no support](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList) for multiple args for `classList.addClass()`...
